=== Nemiroff/kodi_repo/_py3/plugin.video.lostfilm.tv/resources/settings.xsd
<?xml version="1.0" encoding="utf-8"?>
<!-- edited with XMLSpy v2008 sp1 (http://www.altova.com) by anteo (EMBRACE) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="settings">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="category" type="categoryType" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="categoryType">
		<xs:sequence>
			<xs:element name="setting" type="settingType" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="label" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="settingType">
		<xs:attribute name="range" type="xs:string"/>
		<xs:attribute name="id" type="xs:string"/>
		<xs:attribute name="label" type="xs:string"/>
		<xs:attribute name="type" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="sep"/>
					<xs:enumeration value="lsep"/>
					<xs:enumeration value="text"/>
					<xs:enumeration value="ipaddress"/>
					<xs:enumeration value="number"/>
					<xs:enumeration value="slider"/>
					<xs:enumeration value="bool"/>
					<xs:enumeration value="enum"/>
					<xs:enumeration value="labelenum"/>
					<xs:enumeration value="file"/>
					<xs:enumeration value="audio"/>
					<xs:enumeration value="video"/>
					<xs:enumeration value="image"/>
					<xs:enumeration value="executable"/>
					<xs:enumeration value="folder"/>
					<xs:enumeration value="action"/>
					<xs:enumeration value="fileenum"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="default" type="xs:string"/>
		<xs:attribute name="value" type="xs:string"/>
		<xs:attribute name="visible" type="xs:string"/>
		<xs:attribute name="values" type="xs:string"/>
		<xs:attribute name="lvalues" type="xs:string"/>
		<xs:attribute name="subsetting" type="xs:boolean"/>
		<xs:attribute name="enable" type="xs:string"/>
		<xs:attribute name="action" type="xs:string"/>
		<xs:attribute name="option">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="hidden"/>
					<xs:enumeration value="int"/>
					<xs:enumeration value="urlencoded"/>
					<xs:enumeration value="float"/>
					<xs:enumeration value="percent"/>
					<xs:enumeration value="writeable"/>
					<xs:enumeration value="hideext"/>
					<xs:enumeration value="close"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
</xs:schema>

=== Nemiroff/kodi_repo/_py2/plugin.video.lostfilm.tv/resources/settings.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<settings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="settings.xsd">
    <category label="40200">
        <setting type="select" id="host" label="40426" values="lostfilm.uno|lostfilm.run|lostfilm.tv|lostfilm.win" default="lostfilm.win"/>
        <setting type="sep"/>
        <setting type="text" id="login" label="40202"/>
        <setting type="text" id="password" label="40203" option="hidden"/>
        <setting type="number" id="per-page" visible="false" default="15"/>
        <setting type="enum" id="quality" label="40207" lvalues="40211|40208|40209|40210" default="0"/>
        <setting type="bool" id="use_proxy" label="40164" default="false" />
        <setting type="bool" id="show-original-title" label="40212" default="true"/>
        <setting type="bool" id="update-xbmc-library" label="40213" default="true"/>
        <setting type="slider" id="update-library-time" label="40214" default="12" range="1,1,24" option="int"/>
        <setting type="text" id="library-path" visible="false" default="special://userdata/addon_data/plugin.video.lostfilm.tv/library/"/>
        <setting type="bool" id="first-start" visible="false"/>
        <setting type="bool" id="lostfilm-source-created" visible="false"/>
        <setting type="action" label="40406" action="RunPlugin(plugin://plugin.video.lostfilm.tv/create_source)" option="close" visible="eq(-1,false)"/>
        <setting type="bool" id="update-library" visible="false"/>
        <setting type="bool" id="clear-cache" visible="false" default="true"/>
    </category>
    <category label="40100">
        <setting type="enum" id="torrent-stream" label="40101" lvalues="40103|40123" default="1"/>
        <setting type="text" id="ts-host" label="40007" visible="eq(-1,0)" default="127.0.0.1"/>
        <setting type="number" id="ts-port" label="40008" visible="eq(-2,0)" default="8090"/>
        <setting type="slider" id="ts-preload-mb" label="40111" visible="eq(-3,0)" default="20" range="5,5,50" option="int"/>
        <setting type="bool" id="show-playing-progress" label="40118" visible="eq(-4,0)" default="true"/>
    </category>
    <category label="40413">
        <setting type="bool" id="check_only_favorites" label="40414" default="false"/>
        <setting type="bool" id="enable_sync" label="40415" default="true"/>
        <setting type="lsep" label="40416" />
        <setting type="bool" id="sync_add_remove_favorite" label="40417" default="false" visible="eq(-2,true)"/>
        <setting type="bool" id="sync_mark_watch" label="40419" default="true" visible="eq(-3,true)"/>
        <setting type="bool" id="sync_favorites" label="40420" default="false" visible="eq(-4,true)"/>
    </category>
</settings>
